# Generated by Django 2.0.6 on 2020-09-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('file', models.CharField(max_length=100, verbose_name='文件路徑')),
                ('record_date', models.DateField(verbose_name='文件創建日期')),
                ('status', models.IntegerField(choices=[(1, '解析中'), (0, '待解析'), (2, '解析完成')], default=0, verbose_name='狀態')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', verbose_name='大廈名稱')),
                ('meter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Meters', verbose_name='電錶名稱')),
                ('rasp', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Rasps', verbose_name='樹莓派')),
            ],
            options={
                'verbose_name': '已上傳日誌',
                'verbose_name_plural': '已上傳日誌',
                'db_table': 'm_upfiles',
                'ordering': ['record_date'],
            },
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='time',
            field=models.DateTimeField(verbose_name='產生時間'),
        ),
        migrations.AlterUniqueTogether(
            name='uplogs',
            unique_together={('name',)},
        ),
    ]
