# Generated by Django 2.0.6 on 2020-07-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=20)),
                ('v1', models.IntegerField(verbose_name='V1')),
                ('v2', models.IntegerField(verbose_name='V2')),
                ('v3', models.IntegerField(verbose_name='V3')),
                ('l1', models.IntegerField(verbose_name='L1')),
                ('l2', models.IntegerField(verbose_name='L2')),
                ('l3', models.IntegerField(verbose_name='L3')),
                ('pf1', models.IntegerField(verbose_name='PF1')),
                ('pf2', models.IntegerField(verbose_name='PF2')),
                ('pf3', models.IntegerField(verbose_name='PF3')),
                ('kwh', models.IntegerField(verbose_name='KWH')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', to_field='name', verbose_name='大廈名稱')),
            ],
            options={
                'verbose_name': '日統計',
                'verbose_name_plural': '日統計',
                'db_table': 'm_day_count',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='HourCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=20)),
                ('v1', models.IntegerField(verbose_name='V1')),
                ('v2', models.IntegerField(verbose_name='V2')),
                ('v3', models.IntegerField(verbose_name='V3')),
                ('l1', models.IntegerField(verbose_name='L1')),
                ('l2', models.IntegerField(verbose_name='L2')),
                ('l3', models.IntegerField(verbose_name='L3')),
                ('pf1', models.IntegerField(verbose_name='PF1')),
                ('pf2', models.IntegerField(verbose_name='PF2')),
                ('pf3', models.IntegerField(verbose_name='PF3')),
                ('kwh', models.IntegerField(verbose_name='KWH')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', verbose_name='大廈名稱')),
            ],
            options={
                'verbose_name': '小時統計',
                'verbose_name_plural': '小時統計',
                'db_table': 'm_hour_count',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='MinuteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=20)),
                ('v1', models.IntegerField(verbose_name='V1')),
                ('v2', models.IntegerField(verbose_name='V2')),
                ('v3', models.IntegerField(verbose_name='V3')),
                ('l1', models.IntegerField(verbose_name='L1')),
                ('l2', models.IntegerField(verbose_name='L2')),
                ('l3', models.IntegerField(verbose_name='L3')),
                ('pf1', models.IntegerField(verbose_name='PF1')),
                ('pf2', models.IntegerField(verbose_name='PF2')),
                ('pf3', models.IntegerField(verbose_name='PF3')),
                ('kwh', models.IntegerField(verbose_name='KWH')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', verbose_name='大廈名稱')),
            ],
            options={
                'verbose_name': '分鐘統計',
                'verbose_name_plural': '分鐘統計',
                'db_table': 'm_minute_count',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='MonthCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=20)),
                ('v1', models.IntegerField(verbose_name='V1')),
                ('v2', models.IntegerField(verbose_name='V2')),
                ('v3', models.IntegerField(verbose_name='V3')),
                ('l1', models.IntegerField(verbose_name='L1')),
                ('l2', models.IntegerField(verbose_name='L2')),
                ('l3', models.IntegerField(verbose_name='L3')),
                ('pf1', models.IntegerField(verbose_name='PF1')),
                ('pf2', models.IntegerField(verbose_name='PF2')),
                ('pf3', models.IntegerField(verbose_name='PF3')),
                ('kwh', models.IntegerField(verbose_name='KWH')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', verbose_name='大廈名稱')),
            ],
            options={
                'verbose_name': '月統計',
                'verbose_name_plural': '月統計',
                'db_table': 'm_month_count',
                'ordering': ['-dt'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthcount',
            unique_together={('dt',)},
        ),
        migrations.AlterUniqueTogether(
            name='minutecount',
            unique_together={('dt',)},
        ),
        migrations.AlterUniqueTogether(
            name='hourcount',
            unique_together={('dt',)},
        ),
        migrations.AlterUniqueTogether(
            name='daycount',
            unique_together={('dt',)},
        ),
    ]
