# Generated by Django 2.0.6 on 2020-07-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycount',
            name='building',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bases.Buildings', verbose_name='大廈名稱'),
        ),
    ]
